version: '3'

services:
  ui:
    restart: always
    build: ./ui
    ports:
      - '3000:3000'
    volumes: 
      - /todo/ui/src:/app/ui/src
    depends_on:
      - api
  api:
    restart: always
    build: ./api
    volumes: 
      - /todo/api/code:/app/api/code
    ports:
      - '8080:8080'
    depends_on:
      - db
  db:
    restart: always
    image: mongo
    ports:
      - '27017:27017'