version: '3'

services:
  ui:
    build: 
      context: ./ui
      dockerfile: Dockerfile.production 
    volumes: 
      - /todo/ui/src:/app/ui/src
    ports:
      - '8088:80'
    depends_on:
      - api
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.production 
    volumes: 
      - /todo/api/code:/app/api/code
    ports:
      - '8080:8080'
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - '27017:27017'