version: '3'

services:
  ui:
    build: ./ui
    ports:
      - '3000:3000'
    volumes: 
      - C:\Users\kaito\Desktop\pr\todo\ui\src:/app/ui/src
    depends_on:
      - api
  api:
    build: ./api
    volumes: 
      - C:\Users\kaito\Desktop\pr\todo\api\code:/app/api/code
    ports:
      - '8080:8080'
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - '27017:27017'